@echo off
echo Starting Unprecedented Times platform...
echo Waiting for Docker to load...
timeout /t 60 /nobreak
echo Starting Ghost...
docker start ghost
docker start open-webui
echo Starting frontend containers...
docker start frontends
echo Starting Cloudflare tunnel...
start /B cloudflared tunnel --config "C:\Users\User\.cloudflared\config.yml" run unprecedented
echo Starting Cloudflare tunnel watchdog...
start /B C:\Users\User\cloudflared-watchdog.bat
echo All services started.