server {
    listen 4200;
    root /usr/share/nginx/html/mycelium;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 4201;
    root /usr/share/nginx/html/lostfound;
    index index.html;
    location / {
        try_files $uri $uri/ /index.html;
    }
}
